# Generated by Django 5.1.7 on 2025-03-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='master',
            field=models.ManyToManyField(blank=True, default=None, related_name='service', to='main.master', verbose_name='Мастер'),
        ),
    ]
